const mongoose = require("mongoose");
const itemSchema = new mongoose.Schema({
  productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true },
  variantId: { type: mongoose.Schema.Types.ObjectId },
  variantName: String,
  name: String, sku: String, quantity: Number, unitPricePaise: Number, lineTotalPaise: Number
}, { _id: false });
const schema = new mongoose.Schema({
  orderNumber: { type: String, required: true, unique: true },
  shopId: { type: mongoose.Schema.Types.ObjectId, ref: "Shop", required: true, index: true },
  customerId: { type: mongoose.Schema.Types.ObjectId, ref: "User", index: true },
  customerContact: { name: String, phone: String, email: String },
  source: { type: String, enum: ["online", "pos"], default: "online" },
  fulfilmentMode: { type: String, enum: ["walk_in", "pickup", "delivery", "reserve", "express_pickup", "preorder"], required: true },
  items: [itemSchema],
  subtotalPaise: Number,
  discountPaise: { type: Number, default: 0 },
  deliveryFeePaise: { type: Number, default: 0 },
  packagingFeePaise: { type: Number, default: 0 },
  handlingFeePaise: { type: Number, default: 0 },
  platformFeePaise: { type: Number, default: 0 },
  taxPaise: { type: Number, default: 0 },
  taxPercent: { type: Number, default: 0 },
  distanceKm: { type: Number, default: 0 },
  pricingBreakdown: { type: mongoose.Schema.Types.Mixed, default: {} },
  totalPaise: Number,
  paymentMethod: { type: String, enum: ["cash", "upi", "card", "cod", "other"], default: "cash" },
  paymentStatus: { type: String, enum: ["pending", "paid", "failed", "refunded"], default: "pending" },
  status: { type: String, enum: ["placed", "accepted", "preparing", "ready", "out_for_delivery", "completed", "cancelled", "rejected"], default: "placed" },
  timeline:[{status:String,note:String,at:{type:Date,default:Date.now}}],
  address: { line1: String, area: String, city: String, state: String, pincode: String, location: { type: { type: String, enum: ["Point"], default: "Point" }, coordinates: { type: [Number], default: [0,0] } } },
  notes: String,
  assignedDeliveryUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null, index: true },
  deliveryStatus: { type: String, enum: ["unassigned","searching","assigned","handover_verified","picked_up","on_the_way","delivered","failed"], default: "unassigned", index:true },
  deliveryBroadcastAt:{type:Date,default:null},
  deliveryAcceptedAt:{type:Date,default:null},
  deliveryPartnerEarningPaise:{type:Number,default:0},
  pickupHandoverCode:{type:String,default:"",select:false},
  customerDeliveryCode:{type:String,default:"",select:false},
  handoverVerifiedAt:{type:Date,default:null},
  deliveredVerifiedAt:{type:Date,default:null},
  deliveryProofNote: { type: String, default: "" },
  pickupCode: { type: String, default: "" },
  pickupVerifiedAt: { type: Date, default: null },
  completedAt: Date,
  cancelledAt: Date,
  cancelledBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  cancellationReason: { type: String, default: "" }
}, { timestamps: true });
module.exports = mongoose.model("Order", schema);
