import React,{useCallback,useEffect,useState} from 'react';
import {Crosshair,MapPin,Plus,Search,Trash2} from 'lucide-react';
import api from '../../api/client';
import {useLocation} from '../../context/LocationContext';
import './CustomerAddresses.css';

const blank={label:'Home',name:'',phone:'',line1:'',line2:'',city:'',state:'',pincode:'',isDefault:false,addressText:'',location:null};
const point=result=>({type:'Point',coordinates:[Number(result.lng),Number(result.lat)]});
const addressFields=new Set(['line1','line2','city','state','pincode']);

export default function CustomerAddresses(){
 const{persist}=useLocation();
 const[list,setList]=useState([]);const[form,setForm]=useState(blank);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[locating,setLocating]=useState(false);const[results,setResults]=useState([]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const{data}=await api.get('/customer/addresses');setList(Array.isArray(data?.addresses)?data.addresses:[])}catch(e){setError(e.response?.data?.message||'Unable to load addresses')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);

 const applyResult=result=>{const a=result.address||{};setForm(previous=>({...previous,line1:a.house_number?[a.house_number,a.road].filter(Boolean).join(' '):(a.road||a.neighbourhood||a.suburb||previous.line1),line2:a.neighbourhood||a.suburb||'',city:a.city||a.town||a.village||a.county||'',state:a.state||'',pincode:a.postcode||'',addressText:result.label,location:point(result)}));setResults([]);setError('')};
 const detect=async()=>{if(!navigator.geolocation){setError('Location detection is unavailable in this browser.');return}setLocating(true);setError('');navigator.geolocation.getCurrentPosition(async position=>{const lat=Number(position.coords.latitude),lng=Number(position.coords.longitude);setForm(previous=>({...previous,addressText:`${lat.toFixed(6)}, ${lng.toFixed(6)}`,location:{type:'Point',coordinates:[lng,lat]}}));try{const{data}=await api.post('/locations/reverse',{lat,lng});if(data?.result)applyResult(data.result)}catch{setError('Coordinates were pinned, but the readable address could not be loaded. Confirm the text fields before saving.')}finally{setLocating(false)}},e=>{setError(e.message||'Location permission was denied');setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
 const find=async()=>{const text=[form.line1,form.line2,form.city,form.state,form.pincode].filter(Boolean).join(', ');if(!text){setError('Enter an address first.');return}setLocating(true);setError('');try{const{data}=await api.post('/locations/geocode',{address:text});setResults(data.results||[]);if((data.results||[]).length===1)applyResult(data.results[0]);if(!(data.results||[]).length)setError('No matching location found. Add a clearer landmark/city or use Detect live location.')}catch(e){setError(e.response?.data?.message||'Unable to locate this address')}finally{setLocating(false)}};
 const changeField=(key,value)=>setForm(previous=>({...previous,[key]:value,...(addressFields.has(key)&&previous.location?{location:null,addressText:''}:{})}));
 const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{let payload={...form};if(!payload.location){const text=[form.line1,form.line2,form.city,form.state,form.pincode].filter(Boolean).join(', ');const{data}=await api.post('/locations/geocode',{address:text});if(!data.results?.[0])throw new Error('We could not locate this address. Use Detect live location or choose a typed-address result.');payload={...payload,addressText:data.results[0].label,location:point(data.results[0])}}const{data}=await api.post('/customer/addresses',payload);if(payload.isDefault){await persist({label:payload.label,addressText:payload.addressText||[payload.line1,payload.city].join(', '),source:'address',lat:payload.location.coordinates[1],lng:payload.location.coordinates[0]})}setForm(blank);setResults([]);await load();return data}catch(e){setError(e.response?.data?.message||e.message||'Unable to save address')}finally{setSaving(false)}};
 const remove=async id=>{if(!confirm('Remove this address?'))return;try{await api.delete(`/customer/addresses/${id}`);await load()}catch(e){setError(e.response?.data?.message||'Unable to remove address')}};
 return <><div className="portal-heading"><div><span>Delivery details</span><h1>Saved addresses</h1><p>Pin the exact delivery location after entering the address. Editing the address clears the old pin so a different city cannot use stale coordinates.</p></div></div>{error&&<div className="inline-alert error">{error}<button onClick={()=>setError('')}>Close</button></div>}<div className="customer-two-col"><form className="portal-card form-grid address-form" onSubmit={submit}><div className="section-title form-wide"><h2><Plus size={20}/> Add address</h2></div><div className="address-location-actions form-wide"><button type="button" onClick={detect} disabled={locating}><Crosshair/>{locating?'Detecting…':'Detect live location'}</button><button type="button" onClick={find} disabled={locating}><Search/>Find typed address</button>{form.location?<span><MapPin/>Location pinned · {Number(form.location.coordinates?.[1]).toFixed(5)}, {Number(form.location.coordinates?.[0]).toFixed(5)}</span>:<span className="pin-required"><MapPin/>Pin required before saving</span>}</div>{['label','name','phone','line1','line2','city','state','pincode'].map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input required={['name','phone','line1','city','state','pincode'].includes(k)} value={form[k]} onChange={e=>changeField(k,e.target.value)}/></label>)}{results.length>0&&<div className="address-search-results form-wide">{results.map((r,i)=><button type="button" key={i} onClick={()=>applyResult(r)}><MapPin/><span>{r.label}</span></button>)}</div>}<label className="check form-wide"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Make this my default shopping location</label><button className="primary-button form-wide" disabled={saving}>{saving?'Saving…':'Save address'}</button></form><section className="portal-card"><div className="section-title"><h2>Your addresses</h2><span>{list.length}</span></div>{loading?<div className="skeleton-list"><div/><div/></div>:list.map(a=><article className="address-card" key={a._id}><div className="address-pin"><MapPin/></div><div className="address-copy"><b>{a.label} {a.isDefault&&<span>Default</span>}</b><p>{a.name} · {a.phone}</p><p>{a.line1}{a.line2?`, ${a.line2}`:''}, {a.city}, {a.state} - {a.pincode}</p><small>{a.location?.coordinates?.some(Number)?'Exact service location saved':'Location coordinates missing'}</small></div><button className="icon-danger" onClick={()=>remove(a._id)} title="Remove address"><Trash2 size={17}/></button></article>)}{!loading&&!list.length&&<div className="empty-state"><MapPin/><h3>No saved addresses</h3><p>Add an address to make checkout faster.</p></div>}</section></div></>}
