import React,{useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {Store,Truck,PackageCheck,ReceiptText,ShoppingBasket,HeartPulse,Shirt,Smartphone,BookOpen,ChevronRight,MapPin,Star,Clock3,ShieldCheck,Sparkles} from "lucide-react";
import api from "../api/client";
import {useLocation} from "../context/LocationContext";
import "./Home.css";
const cats=[[ShoppingBasket,"Grocery"],[HeartPulse,"Pharmacy"],[Shirt,"Fashion"],[Smartphone,"Mobiles"],[BookOpen,"Stationery"]];
const media=u=>u?(u.startsWith("http")?u:`${import.meta.env.VITE_API_ORIGIN||"http://localhost:5000"}${u}`):"";
export default function Home(){
 const{location,params,setOpen}=useLocation();const[shops,setShops]=useState([]),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!location){setShops([]);return}let active=true;setLoading(true);api.get('/shops',{params}).then(r=>{if(active)setShops((r.data?.shops||[]).slice(0,4))}).catch(()=>{if(active)setShops([])}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[location?.lat,location?.lng]);
 const serviceText=useMemo(()=>location?`Serving ${location.label}`:"Choose your location to unlock nearby stores",[location]);
 return <main className="home-page">
  <section className="home-hero"><div><span className="eyebrow"><Sparkles size={14}/> LOCAL COMMERCE, CONNECTED</span><h1>Your nearby shops,<br/>now in your pocket.</h1><p>Discover verified local stores, compare fulfilment options, order online and keep every digital bill safely in one place.</p><div className="hero-location-line"><MapPin size={18}/><span>{serviceText}</span><button onClick={()=>setOpen(true)}>{location?"Change":"Set location"}</button></div><div className="hero-actions"><Link to="/shops">Explore shops</Link><Link className="secondary" to="/register">Open your shop</Link></div><div className="hero-trust"><span><ShieldCheck/>Admin-approved stores</span><span><Clock3/>Fast pickup</span><span><ReceiptText/>Digital receipts</span></div></div><div className="hero-panel"><div><PackageCheck/><span><b>Pickup ready</b><small>Skip the queue at your local store</small></span></div><div><ReceiptText/><span><b>Digital bill saved</b><small>Receipts linked to phone or email</small></span></div><div><Truck/><span><b>Flexible fulfilment</b><small>Pickup, delivery, reserve or walk-in</small></span></div></div></section>
  <section className="home-section"><div className="section-title"><div><span className="eyebrow">SHOP YOUR WAY</span><h2>Popular categories</h2></div><Link to="/shops">View all <ChevronRight size={18}/></Link></div><div className="category-row">{cats.map(([Icon,n])=><Link to={`/search?q=${encodeURIComponent(n)}`} key={n}><span><Icon/></span><b>{n}</b><small>Explore nearby</small></Link>)}</div></section>
  <section className="home-section nearby-home"><div className="section-title"><div><span className="eyebrow">AROUND YOU</span><h2>Nearby stores ready to serve</h2></div><Link to="/shops">See marketplace <ChevronRight size={18}/></Link></div>{!location?<div className="location-empty-home"><MapPin/><h3>Set a shopping location</h3><p>We only show stores that can actually serve your selected address.</p><button onClick={()=>setOpen(true)}>Choose location</button></div>:loading?<div className="home-shop-grid">{[1,2,3,4].map(x=><div className="shop-skeleton" key={x}/>)}</div>:shops.length?<div className="home-shop-grid">{shops.map(shop=><Link className="home-shop-card" to={`/shops/${shop.slug}`} key={shop._id}><div className="home-shop-cover">{shop.coverUrl?<img src={media(shop.coverUrl)} alt=""/>:<Store/>}<span>{shop.isLive?"Open":"Offline"}</span></div><div className="home-shop-body"><div className="home-shop-logo">{shop.logoUrl?<img src={media(shop.logoUrl)} alt=""/>:shop.name?.[0]}</div><div><h3>{shop.name}</h3><p>{shop.category||"Local store"}</p><div className="shop-meta"><span><MapPin size={14}/>{Number(shop.distanceKm||0).toFixed(1)} km</span><span><Star size={14}/>Verified</span></div></div></div></Link>)}</div>:<div className="location-empty-home"><Store/><h3>No live stores in this radius yet</h3><p>Try another location or check back when local sellers go live.</p><Link to="/shops">Browse marketplace</Link></div>}</section>
  <section className="feature-band"><article><Store/><h3>One storefront</h3><p>Every approved local shop gets a searchable public catalogue.</p></article><article><PackageCheck/><h3>Pickup-first commerce</h3><p>Reserve products, order ahead and collect without waiting.</p></article><article><ReceiptText/><h3>Universal bills</h3><p>Registered and guest customers receive secure digital invoices.</p></article></section><section className="owner-cta"><div><span className="eyebrow">FOR LOCAL BUSINESSES</span><h2>Run your shop from one dashboard</h2><p>Inventory, products, orders, counter billing, customer history and approvals—all connected.</p></div><Link to="/register">Create owner account</Link></section>
 </main>
}
