import React,{useEffect,useMemo,useState} from 'react';
import{Link}from'react-router-dom';
import{AlertTriangle,ArrowDownToLine,ArrowUpFromLine,Boxes,PackageCheck,Search,TrendingDown,WalletCards}from'lucide-react';
import api from'../../api/client';
import useOwnerShop from'./useOwnerShop';
import'./OwnerInventory.css';
const money=p=>`₹${((p||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const movementTypes=[['adjustment','Manual adjustment'],['opening','Opening stock'],['purchase','Purchase / received'],['damage','Damaged stock'],['expiry','Expired stock'],['return','Customer return']];
export default function OwnerInventory(){
  const{shop}=useOwnerShop();
  const[data,setData]=useState({products:[],movements:[]});
  const[form,setForm]=useState({productId:'',quantity:1,type:'adjustment',unitCostPaise:0,note:''});
  const[query,setQuery]=useState('');const[stockFilter,setStockFilter]=useState('all');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
  const load=async()=>{if(!shop)return;setLoading(true);setError('');try{const r=await api.get(`/operations/${shop._id}/inventory`);setData({products:Array.isArray(r.data?.products)?r.data.products:[],movements:Array.isArray(r.data?.movements)?r.data.movements:[]})}catch(e){setError(e.response?.data?.message||'Could not load inventory.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[shop?._id]);
  const summary=useMemo(()=>{const products=data.products,total=products.length,low=products.filter(p=>(p.stockQty||0)<=Number(p.lowStockThreshold||0)&&p.stockQty>0).length,out=products.filter(p=>(p.stockQty||0)<=0).length,value=products.reduce((a,p)=>a+(p.costPricePaise||0)*(p.stockQty||0),0),units=products.reduce((a,p)=>a+Number(p.stockQty||0),0);return{total,low,out,value,units}},[data.products]);
  const filteredProducts=useMemo(()=>data.products.filter(p=>{const q=query.toLowerCase();const match=!q||[p.name,p.sku,p.brand,p.category,p.barcode].some(x=>String(x||'').toLowerCase().includes(q));const low=(p.stockQty||0)<=Number(p.lowStockThreshold||0)&&p.stockQty>0;const out=(p.stockQty||0)<=0;const ok=stockFilter==='all'||(stockFilter==='low'&&low)||(stockFilter==='out'&&out)||(stockFilter==='healthy'&&!low&&!out);return match&&ok}),[data.products,query,stockFilter]);
  const submit=async e=>{e.preventDefault();setError('');setSuccess('');try{await api.post(`/operations/${shop._id}/inventory/adjust`,{...form,quantity:Number(form.quantity),unitCostPaise:Math.round(Number(form.unitCostPaise||0)*100)});setForm({...form,quantity:1,note:''});setSuccess('Inventory movement recorded.');await load()}catch(e){setError(e.response?.data?.message||'Could not record movement.')}};
  if(!shop)return <div className="panel owner-cta-state"><h2>No active shop</h2><p>Select your approved shop before managing inventory.</p><Link className="primary-action" to="/owner/shops">Open My shops</Link></div>;
  return <div className="inventory-workspace"><div className="dash-title inventory-title"><div><span className="eyebrow"><Boxes size={15}/> Stock control</span><h1>Inventory workspace</h1><p>Track availability, value, low stock and every movement for <b>{shop.name}</b>.</p></div><Link className="primary-action" to="/owner/products">+ Add product</Link></div>
    {error&&<div className="owner-alert error">{error}</div>}{success&&<div className="owner-alert success">{success}</div>}
    <section className="inventory-summary"><article><Boxes/><div><span>Total products</span><b>{summary.total}</b><small>{summary.units} units in stock</small></div></article><article className={summary.low?'warning':''}><AlertTriangle/><div><span>Low stock</span><b>{summary.low}</b><small>At or below alert level</small></div></article><article className={summary.out?'danger':''}><TrendingDown/><div><span>Out of stock</span><b>{summary.out}</b><small>Needs restocking</small></div></article><article><WalletCards/><div><span>Inventory value</span><b>{money(summary.value)}</b><small>Based on cost price</small></div></article></section>
    {!data.products.length?<div className="panel owner-cta-state"><h2>Add products first</h2><p>Inventory movements can be recorded after at least one product exists.</p><Link className="primary-action" to="/owner/products">+ Add product</Link></div>:<section className="inventory-adjust-card"><div className="adjust-head"><div><h2>Record stock movement</h2><p>Use positive quantities to add stock and negative quantities to reduce it.</p></div><PackageCheck/></div><form className="inventory-adjust-form" onSubmit={submit}><label>Product<select required value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Select product</option>{data.products.map(p=><option key={p._id} value={p._id}>{p.name} · {p.sku} · Stock {p.stockQty}</option>)}</select></label><label>Movement<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{movementTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Quantity<input type="number" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unit cost ₹<input type="number" min="0" step="0.01" value={form.unitCostPaise} onChange={e=>setForm({...form,unitCostPaise:e.target.value})}/></label><label className="note-field">Note<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Reason, supplier or invoice reference"/></label><button className="primary-action">Record movement</button></form></section>}
    <section className="inventory-catalogue"><header><div><h2>Stock overview</h2><p>Search products and identify products needing attention.</p></div><div className="inventory-filters"><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, SKU or barcode"/></div><select value={stockFilter} onChange={e=>setStockFilter(e.target.value)}><option value="all">All stock</option><option value="healthy">Healthy stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div></header><div className="inventory-table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Available</th><th>Reserved</th><th>Alert level</th><th>Cost</th><th>Stock value</th><th>Status</th></tr></thead><tbody>{filteredProducts.map(p=>{const low=(p.stockQty||0)<=Number(p.lowStockThreshold||0)&&p.stockQty>0,out=(p.stockQty||0)<=0;return <tr key={p._id}><td><b>{p.name}</b><small>{p.brand||p.category||'Product'}</small></td><td>{p.sku}</td><td><b>{p.stockQty||0}</b> {p.unit}</td><td>{p.reservedStockQty||0}</td><td>{p.lowStockThreshold||0}</td><td>{money(p.costPricePaise)}</td><td>{money((p.costPricePaise||0)*(p.stockQty||0))}</td><td><span className={`stock-status ${out?'out':low?'low':'healthy'}`}>{out?'Out of stock':low?'Low stock':'Healthy'}</span></td></tr>})}{!filteredProducts.length&&<tr><td colSpan="8" className="empty-row">No products match these filters.</td></tr>}</tbody></table></div></section>
    <section className="movement-history"><header><div><h2>Movement history</h2><p>Purchases, sales, returns, damage and adjustments.</p></div><div className="movement-legend"><span><ArrowDownToLine/> Added</span><span><ArrowUpFromLine/> Reduced</span></div></header><div className="inventory-table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Quantity</th><th>Unit cost</th><th>Note</th></tr></thead><tbody>{data.movements.map(m=><tr key={m._id}><td>{new Date(m.createdAt).toLocaleString()}</td><td><b>{m.productId?.name||m.productSnapshot?.name||'Deleted product'}</b><small>{m.productId?.sku||m.productSnapshot?.sku||'Historical record'}{m.productId?.status==='archived'?' · Archived':''}</small></td><td>{String(m.type||'').replaceAll('_',' ')}</td><td className={m.quantity>=0?'positive':'negative'}>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.unitCostPaise?money(m.unitCostPaise):'—'}</td><td>{m.note||'—'}</td></tr>)}{!data.movements.length&&<tr><td colSpan="6" className="empty-row">No stock movements recorded yet.</td></tr>}</tbody></table></div></section>
  </div>;
}
