import React,{useEffect,useState} from 'react';
import api from '../../api/client';
import {useWorkspace} from '../../context/WorkspaceContext';
import PageState from '../../components/common/PageState';
import './OwnerEmployees.css';
const roles=['manager','cashier','inventory_manager','accountant','delivery_staff'];
export default function OwnerEmployees(){
  const{activeShop,loading:workspaceLoading,error:workspaceError,refresh}=useWorkspace();
  const[employees,setEmployees]=useState([]);const[invites,setInvites]=useState([]);const[form,setForm]=useState({identifier:'',role:'cashier'});const[inviteLink,setInviteLink]=useState('');const[showForm,setShowForm]=useState(false);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
  const load=async()=>{if(!activeShop)return;setLoading(true);setError('');try{const[a,b]=await Promise.all([api.get(`/workspace/${activeShop._id}/employees`),api.get(`/workspace/${activeShop._id}/invites`)]);setEmployees(Array.isArray(a.data?.employees)?a.data.employees:[]);setInvites(Array.isArray(b.data?.invites)?b.data.invites:[])}catch(e){setError(e.response?.data?.message||'Could not load employees.')}finally{setLoading(false)}};
  useEffect(()=>{if(activeShop)load()},[activeShop?._id]);
  const invite=async e=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{const{data}=await api.post(`/workspace/${activeShop._id}/invites`,form);const link=`${location.origin}${data.acceptPath}`;setInviteLink(link);setSuccess('Invitation created. Share the link with the employee.');setForm({identifier:'',role:'cashier'});await load()}catch(e){setError(e.response?.data?.message||'Could not create invitation. The employee must register using the same phone or email.')}finally{setSaving(false)}};
  const update=async(m,patch)=>{try{await api.patch(`/workspace/${activeShop._id}/employees/${m._id}`,patch);await load()}catch(e){setError(e.response?.data?.message||'Could not update employee.')}};
  if(workspaceLoading)return <PageState title="Loading your shop" message="Preparing employee management…"/>;
  if(workspaceError&&!activeShop)return <PageState title="Shop could not be loaded" message={workspaceError} actionLabel="Retry" onAction={refresh}/>;
  if(!activeShop)return <PageState title="No active shop" message="Create or select a shop before adding employees." actionLabel="Go to My shops" actionTo="/owner/shops"/>;
  return <div className="employee-page"><div className="dash-title owner-page-actions"><div><h1>Employees & permissions</h1><p>Manage the team for <b>{activeShop.name}</b>.</p></div><button className="primary-action" onClick={()=>{setShowForm(v=>!v);setError('');setSuccess('')}}>{showForm?'Close form':'+ Invite employee'}</button></div>
  {error&&<div className="owner-alert error">{error}</div>}{success&&<div className="owner-alert success">{success}</div>}
  {showForm&&<form className="panel invite-card employee-invite-form" onSubmit={invite}><div><h2>Invite employee</h2><p>The employee must first register with the same phone number or email.</p></div><input required placeholder="Employee email or verified phone" value={form.identifier} onChange={e=>setForm({...form,identifier:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><div className="form-actions"><button type="button" className="secondary-action" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary-action" disabled={saving}>{saving?'Creating invite…':'Create invitation'}</button></div>{inviteLink&&<div className="invite-link"><b>Invitation link</b><code>{inviteLink}</code><button type="button" onClick={()=>navigator.clipboard.writeText(inviteLink)}>Copy link</button></div>}</form>}
  <section className="panel"><div className="panel-head"><div><h2>Team members</h2><p>{employees.length} employee{employees.length===1?'':'s'} joined</p></div>{!showForm&&<button className="secondary-action" onClick={()=>setShowForm(true)}>Invite employee</button>}</div>{loading?<p>Loading employees…</p>:<div className="employee-list">{employees.length?employees.map(m=><article key={m._id}><div className="employee-avatar">{m.userId?.name?.[0]||'E'}</div><div><b>{m.userId?.name||'Employee'}</b><small>{m.userId?.email||m.userId?.phone}</small></div><select value={m.role} onChange={e=>update(m,{role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><button className={m.status==='active'?'danger':'secondary'} onClick={()=>update(m,{status:m.status==='active'?'revoked':'active'})}>{m.status==='active'?'Revoke':'Restore'}</button></article>):<div className="employee-empty"><h3>No employees yet</h3><p>Invite a cashier, manager, inventory manager, accountant or delivery employee.</p><button className="primary-action" onClick={()=>setShowForm(true)}>+ Invite first employee</button></div>}</div>}</section>
  <section className="panel"><div className="panel-head"><h2>Pending invitations</h2></div>{invites.length?<div className="invite-table">{invites.map(i=><div key={i._id}><span>{i.identifier}</span><span>{i.role.replaceAll('_',' ')}</span><span className={`status-pill ${i.status}`}>{i.status}</span><small>{new Date(i.expiresAt).toLocaleDateString()}</small></div>)}</div>:<p>No pending invitations.</p>}</section></div>;
}
