import React,{useCallback,useEffect,useMemo,useState}from"react";
import api from"../../api/client";
import PageState from"../../components/common/PageState";
import"./admin.css";

export default function AdminDeliveryPricing(){
 const[settings,setSettings]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);const{data}=await api.get("/governance/settings");setSettings(data.settings);setError("")}catch(e){setError(e.response?.data?.message||"Could not load delivery pricing")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const tiers=useMemo(()=>[...(settings?.deliveryFeeTiers||[])].sort((a,b)=>Number(a.uptoKm)-Number(b.uptoKm)),[settings]);
 const updateTier=(index,key,value)=>setSettings(current=>({...current,deliveryFeeTiers:(current.deliveryFeeTiers||[]).map((tier,i)=>i===index?{...tier,[key]:Number(value)}:tier)}));
 const addTier=()=>setSettings(current=>({...current,deliveryFeeTiers:[...(current.deliveryFeeTiers||[]),{uptoKm:1,feePaise:0}]}));
 const removeTier=index=>setSettings(current=>({...current,deliveryFeeTiers:(current.deliveryFeeTiers||[]).filter((_,i)=>i!==index)}));
 const save=async()=>{try{setSaving(true);setMessage("");const normalized=[...(settings.deliveryFeeTiers||[])].map(t=>({uptoKm:Number(t.uptoKm),feePaise:Math.round(Number(t.feePaise))})).filter(t=>t.uptoKm>0&&t.feePaise>=0).sort((a,b)=>a.uptoKm-b.uptoKm);if(!normalized.length)throw new Error("Add at least one valid delivery tier");for(let i=1;i<normalized.length;i++)if(normalized[i].uptoKm<=normalized[i-1].uptoKm)throw new Error("Distance tiers must increase without duplicates");const{data}=await api.patch("/governance/settings",{deliveryFeeTiers:normalized,platformFeePaise:Math.max(0,Math.round(Number(settings.platformFeePaise||0))),reason:"Delivery pricing updated from admin dashboard"});setSettings(data.settings);setMessage("Delivery pricing saved. New checkout calculations use these charges immediately.")}catch(e){setMessage(e.response?.data?.message||e.message||"Could not save delivery pricing")}finally{setSaving(false)}};
 return <PageState loading={loading} error={error} onRetry={load}>{settings&&<div className="delivery-pricing-page"><div className="admin-title"><div><h1>Delivery charges</h1><p>Control distance-based delivery fees and the platform fee used during checkout.</p></div><button className="primary-action" disabled={saving} onClick={save}>{saving?"Saving…":"Save delivery charges"}</button></div>{message&&<div className="pricing-message" role="status">{message}</div>}<section className="admin-panel pricing-overview"><div><b>Pickup, walk-in and reserve</b><span>₹0 delivery fee</span></div><div><b>Delivery</b><span>Calculated from shop-to-address distance</span></div><div><b>Security</b><span>Backend recalculates every total</span></div></section><section className="admin-panel"><div className="panel-heading"><div><h2>Distance slabs</h2><p>The first slab whose distance covers the customer is applied.</p></div><button type="button" onClick={addTier}>+ Add slab</button></div><div className="delivery-tier-list">{(settings.deliveryFeeTiers||[]).map((tier,index)=><article className="delivery-tier-card" key={`${index}-${tier.uptoKm}`}><span className="tier-number">{index+1}</span><label><span>Up to distance</span><div className="input-suffix"><input type="number" min="0.1" step="0.1" value={tier.uptoKm} onChange={e=>updateTier(index,"uptoKm",e.target.value)}/><b>km</b></div></label><label><span>Delivery charge</span><div className="input-prefix"><b>₹</b><input type="number" min="0" step="1" value={(tier.feePaise||0)/100} onChange={e=>updateTier(index,"feePaise",Number(e.target.value)*100)}/></div></label><button className="danger-action" type="button" onClick={()=>removeTier(index)} disabled={(settings.deliveryFeeTiers||[]).length===1}>Remove</button></article>)}</div></section><section className="admin-panel platform-fee-card"><div><h2>Platform fee</h2><p>Optional fixed charge added once per shop order.</p></div><label><span>Fee per order</span><div className="input-prefix"><b>₹</b><input type="number" min="0" step="1" value={(settings.platformFeePaise||0)/100} onChange={e=>setSettings(v=>({...v,platformFeePaise:Number(e.target.value)*100}))}/></div></label></section><section className="admin-panel pricing-preview"><h2>Current customer preview</h2>{tiers.map(t=><div key={t.uptoKm}><span>Up to {t.uptoKm} km</span><b>₹{((t.feePaise||0)/100).toFixed(2)}</b></div>)}<div><span>Pickup / Walk-in / Reserve</span><b>Free</b></div></section></div>}</PageState>
}
